spring:
  main:
    allow-bean-definition-overriding: true

aws:
  s3:
    bucket: eungbeanbucket
  region:
    static: ap-southeast-2
    auto: false
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

jasypt :
  encryptor :
    key : ${jasypt-key}
    algorithm: PBEWithMD5AndDES